name: Firebase Hosting Continuous Deployment

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GSCONRAD_EXPENSE_TRACKER }}'
          channelId: live
          projectId: gsconrad-expense-tracker
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
